import type { Section } from '@/types';

export const SECTIONS: Section[] = [
  {
    key: 'perfil_valores',
    title: 'Perfil e Valores Pessoais',
    description: 'Esta seção avalia sua autopercepção, motivações e como você interage em ambientes colaborativos e de mudança.',
    color: 'bg-pioneer',
    textColor: 'text-pioneer-foreground',
    statements: [
      'Sinto-me energizado(a) ao colaborar com pessoas de perfis diversos.',
      'Tenho clareza sobre meus principais motivadores internos no trabalho.',
      'Reconheço e gerencio meus sabotadores (medos, vieses) quando surgem.',
      'Busco feedback construtivo para aprimorar minhas ideias.',
      'Demonstro curiosidade e aprendizado contínuo em novas áreas.',
      'Adapto-me rapidamente a mudanças de direção nos projetos.',
      'Mantenho equilíbrio emocional sob pressão.',
      'Alinho minhas metas pessoais com os objetivos estratégicos da organização.',
    ],
  },
  {
    key: 'estilo_cognitivo',
    title: 'Estilo Cognitivo',
    description: 'Esta seção foca em como você aborda problemas, toma decisões e equilibra a necessidade de estrutura com a liberdade para inovar.',
    color: 'bg-driver',
    textColor: 'text-driver-foreground',
    statements: [
      'Prefiro seguir procedimentos estabelecidos ao enfrentar desafios.',
      'Exploro ideias não convencionais mesmo que envolvam riscos.',
      'Valorizo análises detalhadas antes de propor mudanças.',
      'Sinto-me confortável improvisando e testando hipóteses.',
      'Busco dados e evidências sólidas antes de decidir.',
      'Tomo decisões rápidas quando vejo oportunidade de inovação.',
      'Respeito padrões e estruturas existentes.',
      'Aceito ambiguidade e incerteza como parte do processo criativo.',
    ],
  },
  {
    key: 'maturidade_inovacao',
    title: 'Maturidade em Inovação',
    description: 'Esta seção avalia as práticas, processos e investimentos da sua organização para fomentar um ecossistema de inovação sustentável.',
    color: 'bg-integrator',
    textColor: 'text-integrator-foreground',
    statements: [
      'Destinamos verba específica para P&D e projetos-piloto.',
      'Há registro formal dos aprendizados de cada experimento.',
      'Utilizamos metodologias ágeis (Scrum, Kanban) em iniciativas de inovação.',
      'Existe um processo padronizado para submeter e avaliar ideias.',
      'Parcerias externas (startups, universidades) são fomentadas.',
      'Medimos o retorno (financeiro ou operacional) dos projetos inovadores.',
      'Aplicamos abordagem “fail fast, learn fast” nos testes.',
      'Investimos em tecnologias emergentes e capacitação.',
    ],
  },
  {
    key: 'ambiente_governanca',
    title: 'Ambiente de Negócio e Governança',
    description: 'Esta seção mede o suporte da liderança, os mecanismos de governança e os incentivos que habilitam a inovação no dia a dia.',
    color: 'bg-guardian',
    textColor: 'text-guardian-foreground',
    statements: [
      'Recebo apoio claro da liderança executiva para iniciativas inovadoras.',
      'Há uma plataforma ou fórum formal de gestão de ideias.',
      'KPIs específicos de inovação estão definidos e são monitorados.',
      'Funcionários são reconhecidos e recompensados por contribuições inovadoras.',
      'Orçamento para testes e experimentos é aprovado e disponível.',
      'Revisões periódicas acompanham o progresso dos projetos.',
      'A governança da inovação (comitê, papéis) está documentada.',
      'Critérios de aprovação e escalonamento de projetos são transparentes.',
    ],
  },
  {
    key: 'traits_compartilhados',
    title: 'Traits Compartilhados',
    description: 'Esta seção avalia características de transição entre perfis adjacentes.',
    color: 'bg-trait',
    textColor: 'text-trait-foreground',
    statements: [
      'Quando enfrento um desafio, abraço o risco e decido rapidamente, mesmo que precise revisar minha decisão depois.',
      'Valorizo o trabalho individual e a disciplina tanto quanto a velocidade na execução de tarefas.',
      'Confio em processos testados, ao mesmo tempo em que busco construir relacionamentos antes de agir.',
      'Demonstro flexibilidade e empatia, mas também gosto de testar novas ideias sem medo de errar.',
    ],
  },
  {
    key: 'subtipos_internos',
    title: 'Subtipos Internos',
    description: 'Esta seção ajuda a distinguir subperfis dentro de cada quadrante principal.',
    color: 'bg-subtype',
    textColor: 'text-subtype-foreground',
    statements: [
      'Gosto de tomar decisões de forma assertiva e visível para toda a equipe.',
      'Prefiro explorar profundamente dados antes de compartilhar minhas conclusões.',
      'Sou energizado(a) por discussões em grupo e troca de ideias.',
      'Gosto de refletir sozinho(a) e apresentar ideias já amadurecidas.',
      'Procuro ativamente cenários inéditos, mesmo sem garantia de sucesso.',
      'Planejo etapas antes de saltar em novas iniciativas, equilibrando risco.',
      'Mantenho foco rígido em regras, cronogramas e conformidade.',
      'Valorizo proteger e aprimorar processos que já funcionam bem.',
    ],
  },
];
